import { Injectable } from '@nestjs/common';
import { LivestockRepository } from '@infrastructure/repositories/livestock.repository';
import { CreateLivestockDto, UpdateLivestockDto, LivestockDto } from '@application/dtos/livestock.dto';
import { Livestock } from '@domain/entities/livestock.entity';
import { EntityNotFoundException } from '@domain/exceptions/domain.exception';
import { LivestockStatus } from '@domain/enums/livestock.enum';

@Injectable()
export class LivestockService {
    constructor(private readonly livestockRepository: LivestockRepository) { }

    async create(dto: CreateLivestockDto): Promise<LivestockDto> {
        const entity = new Livestock(
            0, // ID generated by DB
            dto.name,
            dto.type,
            dto.quantity || 1,
            dto.status || LivestockStatus.HEALTHY,
            dto.addedDate ? new Date(dto.addedDate) : new Date(),
            dto.tankId,
            dto.scientificName,
            dto.fishbaseId,
            dto.imageUrl,
        );
        const saved = await this.livestockRepository.save(entity);
        return LivestockDto.fromEntity(saved);
    }

    async findByTankId(tankId: number): Promise<LivestockDto[]> {
        const items = await this.livestockRepository.findByTankId(tankId);
        return LivestockDto.fromEntities(items);
    }

    async findById(id: number): Promise<LivestockDto> {
        const item = await this.livestockRepository.findById(id);
        if (!item) {
            throw new EntityNotFoundException('Livestock', id);
        }
        return LivestockDto.fromEntity(item);
    }

    async update(id: number, dto: UpdateLivestockDto): Promise<LivestockDto> {
        const item = await this.livestockRepository.findById(id);
        if (!item) {
            throw new EntityNotFoundException('Livestock', id);
        }

        item.updateDetails(dto.name, dto.scientificName, dto.imageUrl, dto.addedDate ? new Date(dto.addedDate) : undefined);

        if (dto.quantity !== undefined) {
            item.updateQuantity(dto.quantity);
        }

        if (dto.status) {
            item.updateStatus(dto.status);
        }

        const updated = await this.livestockRepository.update(id, item);
        return LivestockDto.fromEntity(updated);
    }

    async delete(id: number): Promise<void> {
        const item = await this.livestockRepository.findById(id);
        if (!item) {
            throw new EntityNotFoundException('Livestock', id);
        }
        await this.livestockRepository.delete(id);
    }
}
